// Turns the .ttf files into a JavaScript module, before every build.
//
// The renderer used to read the fonts off disk with import.meta.url. That
// works locally and fails on Vercel: the server bundle is rolled up into a
// single entry.mjs at a different depth, so the relative path no longer points
// anywhere, and the .ttf files are not copied into the function at all. A
// build here confirmed it — `find .vercel -name "*.ttf"` came back empty.
//
// Base64 in a module sidesteps the whole class of problem. There is no path to
// resolve, no file to copy and nothing to go wrong at runtime in a way that
// only shows up in production. It costs about 570KB of generated JavaScript,
// which is a fair price for a renderer that cannot fail to find its fonts.
//
// The .ttf files stay in the repo as the source of truth. This output is
// generated and gitignored. npm runs it automatically via the prebuild hook,
// on Vercel as well as locally.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const DIR = fileURLToPath(new URL('../src/fonts/', import.meta.url));
const OUT = DIR + 'fonts.generated.js';

const files = readdirSync(DIR).filter((f) => f.endsWith('.ttf')).sort();
if (!files.length) {
  console.error('inline-fonts: no .ttf files in src/fonts/');
  process.exit(1);
}

const key = (f) => f.replace(/\.ttf$/, '').replace(/[^A-Za-z0-9]/g, '_');

let out = '// GENERATED by scripts/inline-fonts.mjs. Do not edit, do not commit.\n';
out += '// Source of truth is the .ttf files beside this one.\n\n';
out += 'const d = (s) => Buffer.from(s, "base64");\n\n';

let total = 0;
for (const f of files) {
  const buf = readFileSync(DIR + f);
  total += buf.length;
  out += `export const ${key(f)} = d(${JSON.stringify(buf.toString('base64'))});\n`;
}

writeFileSync(OUT, out);
console.log(
  `inline-fonts: ${files.length} fonts, ${(total / 1024).toFixed(0)}KB raw ` +
  `-> ${(out.length / 1024).toFixed(0)}KB module`,
);
